# Generated by Django 5.1.6 on 2025-02-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gps_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('picture_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
